version: "3.9"

services:
  openqda:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENQDA_GIT_URL: ${OPENQDA_GIT_URL}
        OPENQDA_GIT_REF: ${OPENQDA_GIT_REF:-main}
        OPENQDA_APP_SUBDIR: ${OPENQDA_APP_SUBDIR:-web}
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:${APP_PORT:-8000}}
      ASSET_URL: ${ASSET_URL:-http://localhost:${APP_PORT:-8000}}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-"*"}
      FORCE_HTTPS: ${FORCE_HTTPS:-false}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-openqda}
      DB_USERNAME: ${DB_USERNAME:-sail}
      DB_PASSWORD: ${DB_PASSWORD:-password}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      REVERB_APP_ID: ${REVERB_APP_ID:-local}
      REVERB_APP_KEY: ${REVERB_APP_KEY:-local-key}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET:-local-secret}
      VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY:-"${REVERB_APP_KEY}"}
      VITE_REVERB_HOST: ${VITE_REVERB_HOST:-localhost}
      VITE_REVERB_PORT: ${VITE_REVERB_PORT:-8443}
      VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME:-https}
      REVERB_SCHEME: ${REVERB_SCHEME:-https}
      REVERB_SERVER_HOST: ${REVERB_SERVER_HOST:-0.0.0.0}
      REVERB_SERVER_PORT: ${REVERB_SERVER_PORT:-8443}
      REVERB_SSL_CERT: /etc/letsencrypt/live/openqda.ils.local/cert.pem
      REVERB_SSL_KEY: /etc/letsencrypt/live/openqda.ils.local/privkey.pem}
      REVERB_SSL_CA: /etc/letsencrypt/live/openqda.ils.local/fullchain.pem}

      # Verhalten beim Start
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-true}
      RUN_SEED: ${RUN_SEED:-true}
      RUN_STORAGE_LINK: ${RUN_STORAGE_LINK:-true}
      RUN_DEBUG_SERVICES_SCRIPT: ${RUN_DEBUG_SERVICES_SCRIPT:-false}
    ports:
      - "${APP_PORT:-8923}:8000"
      - "${REVERB_PORT:-8443}:8443"
    volumes:
      - ./certs:/opt/certs
      ## certs - necessary if REVERB_SSL_CERT, REVERB_SSL_KEY, or REVERB_SSL_CA 
      ## point to files outside the container
      # e.g. ubuntu/debian
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # overwrite entrypoint for local development
      - ./entrypoint.sh:/opt/openqda/entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-openqda}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./openqda-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      retries: 20
      timeout: 5s

  redis:
    image: redis:7-alpine
    volumes:
      - ./openqda-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 20
      timeout: 5s

#volumes:
#  openqda-mysql:
#  openqda-redis:
